title: "Akispace.net - English teaching"
description: "English teaching in Paris, France."
url: "https://akispace.net"
author:
  name: "Akispace.net"
  email: "aki@akispace.net"
  url: "https://akispace.net"

baseurl: /

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

include: ['_pages']

# Custom variables
version: "1.0.0"

# Options
permalink: pretty
custom_header: false
custom_nav_footer: false
reverse: false
